services:
  web:
    build: ./nginx
    ports:
      - "80:80"
      - "4242:4242"
    networks:
      - tor-network
  tor:
    build: ./tor
    volumes:
      - ./tor/data:/var/lib/tor
    networks:
      - tor-network

networks:
  tor-network:
  