//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t __do_global_dtors_aux(void);
int32_t __x86_get_pc_thunk_bx(int32_t a1);
int32_t __x86_get_pc_thunk_dx(int32_t a1);
int32_t _fini(void);
int32_t _init(void);
int32_t _start(int32_t a1);
int32_t deregister_tm_clones(void);
int32_t frame_dummy(void);
int32_t function_1040(char * s1, char * s2);
int32_t function_1050(int32_t main2, int32_t argc, char ** ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)());
int32_t function_1060(char * format, ...);
int32_t function_1070(char * format, ...);
int32_t function_1080(void);
int32_t function_10bc(int32_t a1);
int32_t register_tm_clones(void);

// --------------------- Global Variables ---------------------

int32_t g1;

// ------- Dynamically Linked Functions Without Header --------

int32_t __libc_start_main(int32_t a1, int32_t a2, char ** a3, void (*a4)(), void (*a5)(), void (*a6)());

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x1024
int32_t _init(void) {
    // 0x1000
    int32_t v1; // 0x1000
    __x86_get_pc_thunk_bx(v1);
    return *(int32_t *)(v1 + 0x2fe7);
}

// Address range: 0x1040 - 0x1046
int32_t function_1040(char * s1, char * s2) {
    // 0x1040
    return strcmp(s1, s2);
}

// Address range: 0x1050 - 0x1056
int32_t function_1050(int32_t main2, int32_t argc, char ** ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)()) {
    // 0x1050
    return __libc_start_main(main2, argc, ubp_av, init, fini, rtld_fini);
}

// Address range: 0x1060 - 0x1066
int32_t function_1060(char * format, ...) {
    // 0x1060
    return printf(format);
}

// Address range: 0x1070 - 0x1076
int32_t function_1070(char * format, ...) {
    // 0x1070
    return scanf(format);
}

// Address range: 0x1080 - 0x1086
int32_t function_1080(void) {
    // 0x1080
    int32_t result; // 0x1080
    return result;
}

// Address range: 0x1090 - 0x10bc
int32_t _start(int32_t a1) {
    // 0x1090
    int32_t v1; // 0x1090
    function_10bc(v1);
    int32_t v2 = *(int32_t *)(v1 + 0x2f54); // 0x10b0
    int32_t v3; // 0x1090
    __libc_start_main(v2, a1, (char **)&v3, NULL, NULL, (void (*)())&g1);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x10bc - 0x10c0
int32_t function_10bc(int32_t a1) {
    // 0x10bc
    int32_t result; // 0x10bc
    return result;
}

// Address range: 0x10c0 - 0x10c4
int32_t __x86_get_pc_thunk_bx(int32_t a1) {
    // 0x10c0
    int32_t result; // 0x10c0
    return result;
}

// Address range: 0x10d0 - 0x1109
int32_t deregister_tm_clones(void) {
    // 0x10d0
    __x86_get_pc_thunk_dx((int32_t)&g1);
    int32_t v1; // 0x10d0
    return v1 + 0x2f4f;
}

// Address range: 0x1110 - 0x1157
int32_t register_tm_clones(void) {
    // 0x1110
    __x86_get_pc_thunk_dx((int32_t)&g1);
    return 0;
}

// Address range: 0x1160 - 0x11ab
int32_t __do_global_dtors_aux(void) {
    // 0x1160
    int32_t v1; // 0x1160
    int32_t result = __x86_get_pc_thunk_bx(v1); // 0x1168
    char * v2 = (char *)(v1 + 0x2eb7); // 0x1176
    if (*v2 != 0) {
        // 0x11a6
        return result;
    }
    // 0x117f
    if (*(int32_t *)(v1 + 0x2e83) != 0) {
        // 0x1189
        function_1080();
    }
    int32_t result2 = deregister_tm_clones(); // 0x119a
    *v2 = 1;
    // 0x11a6
    return result2;
}

// Address range: 0x11b0 - 0x11b9
int32_t frame_dummy(void) {
    // 0x11b0
    return register_tm_clones();
}

// Address range: 0x11b9 - 0x11bd
int32_t __x86_get_pc_thunk_dx(int32_t a1) {
    // 0x11b9
    int32_t result; // 0x11b9
    return result;
}

// Address range: 0x11c0 - 0x127c
int main(int argc, char ** argv) {
    // 0x11c0
    int32_t v1; // 0x11c0
    int32_t str2 = *(int32_t *)(v1 + 3641); // bp-126, 0x11e6
    printf((char *)(v1 + 3655));
    scanf((char *)(v1 + 3674));
    int32_t v2 = &str2; // 0x1237
    int32_t str; // bp-112, 0x11c0
    if (strcmp((char *)&str, (char *)&str2) != 0) {
        // 0x1260
        printf((char *)(v2 - 0x1fc9));
    } else {
        // 0x124a
        printf((char *)(v2 - 0x1fd4));
    }
    // 0x1271
    return 0;
}

// Address range: 0x127c - 0x1294
int32_t _fini(void) {
    // 0x127c
    int32_t v1; // 0x127c
    return __x86_get_pc_thunk_bx(v1);
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (11.3.0)
// Detected functions: 16

