//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

// ------------------- Function Prototypes --------------------

int32_t __do_global_dtors_aux(void);
int32_t __x86_get_pc_thunk_bx(int32_t a1);
int32_t __x86_get_pc_thunk_dx(int32_t a1);
int32_t _fini(void);
int32_t _init(void);
int32_t _start(int32_t a1);
int32_t deregister_tm_clones(void);
int32_t frame_dummy(void);
int32_t function_1040(char * s1, char * s2);
int32_t function_1050(int32_t main2, int32_t argc, char ** ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)());
int32_t function_1060(char * format, ...);
int32_t function_1070(struct _IO_FILE * stream);
int32_t function_1080(char * s);
void function_1090(int32_t status);
int32_t function_10a0(char * s);
int32_t * function_10b0(int32_t * s, int32_t c, int32_t n2);
int32_t function_10c0(char * format, ...);
int32_t function_10d0(char * nptr);
int32_t function_10e0(void);
int32_t function_111c(int32_t a1);
int32_t n(int32_t a1);
int32_t no(void);
int32_t ok(int32_t a1);
int32_t register_tm_clones(void);
int32_t ww(int32_t a1);
int32_t xd(int32_t a1);
int32_t xxd(int32_t a1);
int32_t xxxd(int32_t a1);
int32_t xyxxd(int32_t a1);

// --------------------- Global Variables ---------------------

int32_t g1;

// ------- Dynamically Linked Functions Without Header --------

int32_t __libc_start_main(int32_t a1, int32_t a2, char ** a3, void (*a4)(), void (*a5)(), void (*a6)());

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x1024
int32_t _init(void) {
    // 0x1000
    int32_t v1; // 0x1000
    __x86_get_pc_thunk_bx(v1);
    return *(int32_t *)(v1 + 0x5fe3);
}

// Address range: 0x1040 - 0x1046
int32_t function_1040(char * s1, char * s2) {
    // 0x1040
    return strcmp(s1, s2);
}

// Address range: 0x1050 - 0x1056
int32_t function_1050(int32_t main2, int32_t argc, char ** ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)()) {
    // 0x1050
    return __libc_start_main(main2, argc, ubp_av, init, fini, rtld_fini);
}

// Address range: 0x1060 - 0x1066
int32_t function_1060(char * format, ...) {
    // 0x1060
    return printf(format);
}

// Address range: 0x1070 - 0x1076
int32_t function_1070(struct _IO_FILE * stream) {
    // 0x1070
    return fflush(stream);
}

// Address range: 0x1080 - 0x1086
int32_t function_1080(char * s) {
    // 0x1080
    return puts(s);
}

// Address range: 0x1090 - 0x1096
void function_1090(int32_t status) {
    // 0x1090
    exit(status);
}

// Address range: 0x10a0 - 0x10a6
int32_t function_10a0(char * s) {
    // 0x10a0
    return strlen(s);
}

// Address range: 0x10b0 - 0x10b6
int32_t * function_10b0(int32_t * s, int32_t c, int32_t n2) {
    // 0x10b0
    return memset(s, c, n2);
}

// Address range: 0x10c0 - 0x10c6
int32_t function_10c0(char * format, ...) {
    // 0x10c0
    return scanf(format);
}

// Address range: 0x10d0 - 0x10d6
int32_t function_10d0(char * nptr) {
    // 0x10d0
    return atoi(nptr);
}

// Address range: 0x10e0 - 0x10e6
int32_t function_10e0(void) {
    // 0x10e0
    int32_t result; // 0x10e0
    return result;
}

// Address range: 0x10f0 - 0x111c
int32_t _start(int32_t a1) {
    // 0x10f0
    int32_t v1; // 0x10f0
    function_111c(v1);
    int32_t v2 = *(int32_t *)(v1 + 0x5ef4); // 0x1110
    int32_t v3; // 0x10f0
    __libc_start_main(v2, a1, (char **)&v3, NULL, NULL, (void (*)())&g1);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x111c - 0x1120
int32_t function_111c(int32_t a1) {
    // 0x111c
    int32_t result; // 0x111c
    return result;
}

// Address range: 0x1120 - 0x1124
int32_t __x86_get_pc_thunk_bx(int32_t a1) {
    // 0x1120
    int32_t result; // 0x1120
    return result;
}

// Address range: 0x1130 - 0x1169
int32_t deregister_tm_clones(void) {
    // 0x1130
    __x86_get_pc_thunk_dx((int32_t)&g1);
    int32_t v1; // 0x1130
    return v1 + 0x5f07;
}

// Address range: 0x1170 - 0x11b7
int32_t register_tm_clones(void) {
    // 0x1170
    __x86_get_pc_thunk_dx((int32_t)&g1);
    return 0;
}

// Address range: 0x11c0 - 0x120b
int32_t __do_global_dtors_aux(void) {
    // 0x11c0
    int32_t v1; // 0x11c0
    int32_t result = __x86_get_pc_thunk_bx(v1); // 0x11c8
    char * v2 = (char *)(v1 + 0x5e6f); // 0x11d6
    if (*v2 != 0) {
        // 0x1206
        return result;
    }
    // 0x11df
    if (*(int32_t *)(v1 + 0x5e1f) != 0) {
        // 0x11e9
        function_10e0();
    }
    int32_t result2 = deregister_tm_clones(); // 0x11fa
    *v2 = 1;
    // 0x1206
    return result2;
}

// Address range: 0x1210 - 0x1219
int32_t frame_dummy(void) {
    // 0x1210
    return register_tm_clones();
}

// Address range: 0x1219 - 0x121d
int32_t __x86_get_pc_thunk_dx(int32_t a1) {
    // 0x1219
    int32_t result; // 0x1219
    return result;
}

// Address range: 0x1220 - 0x1253
int32_t no(void) {
    // 0x1220
    int32_t v1; // 0x1220
    puts((char *)(v1 + 3548));
    exit(1);
    return &g1;
}

// Address range: 0x1260 - 0x129b
int32_t xd(int32_t a1) {
    // 0x1260
    int32_t v1; // 0x1260
    puts((char *)(v1 + 3490));
    return puts((char *)(v1 + 0x1860));
}

// Address range: 0x12a0 - 0x12c5
int32_t ok(int32_t a1) {
    // 0x12a0
    int32_t v1; // 0x12a0
    return puts((char *)(v1 + 0x1a67));
}

// Address range: 0x12d0 - 0x1490
int main(int argc, char ** argv) {
    // 0x12d0
    int32_t v1; // 0x12d0
    printf((char *)(v1 + 0x1a3f));
    if (scanf((char *)(v1 + 0x1a52)) != 1) {
        // 0x1324
        no();
        // UNREACHABLE
    }
    char v2; // 0x12d0
    if (v2 != 48) {
        // 0x133d
        no();
        // UNREACHABLE
    }
    if (v2 != 48) {
        // 0x1356
        no();
        // UNREACHABLE
    }
    // 0x135e
    int32_t v3; // bp-4, 0x12d0
    int32_t v4 = &v3; // 0x12d1
    fflush((struct _IO_FILE *)*(int32_t *)*(int32_t *)(v1 + 0x5d18));
    int32_t str; // bp-33, 0x12d0
    memset(&str, 0, 9);
    str = 100;
    int32_t v5; // 0x12d0
    int32_t v6; // 0x12d0
    if (strlen((char *)&str) >= 8) {
        // 0x135e
        v5 = v4 - 29;
        v6 = 1;
    } else {
        int32_t v7 = v4 - 29;
        int32_t v8 = 1; // 0x143f
        int32_t v9 = 2; // 0x12d0
        char str2; // bp-57, 0x12d0
        uint32_t len = strlen(&str2); // 0x13dc
        v5 = v7;
        v6 = v8;
        while (v9 < len) {
            char str3 = *(char *)(v4 - 53 + v9); // bp-61, 0x1408
            *(char *)(v8 + v7) = (char)atoi(&str3);
            v8++;
            uint32_t len2 = strlen((char *)&str); // 0x13b7
            v9 += 3;
            v5 = v7;
            v6 = v8;
            if (len2 >= 8) {
                // break -> 0x144a
                break;
            }
            len = strlen(&str2);
            v5 = v7;
            v6 = v8;
        }
    }
    // 0x144a
    *(char *)(v6 + v5) = 0;
    if (strcmp((char *)&str, (char *)(v1 + 0x1a57)) != 0) {
        // 0x1480
        no();
        // UNREACHABLE
    }
    // 0x1473
    ok((int32_t)&g1);
    return 0;
}

// Address range: 0x1490 - 0x14cb
int32_t xxd(int32_t a1) {
    // 0x1490
    int32_t v1; // 0x1490
    puts((char *)(v1 + 0x18a0));
    return puts((char *)(v1 + 0x2360));
}

// Address range: 0x14d0 - 0x14f5
// Demangled:     __int128
int32_t n(int32_t a1) {
    // 0x14d0
    int32_t v1; // 0x14d0
    return puts((char *)(v1 + 0x2569));
}

// Address range: 0x1500 - 0x153b
int32_t xxxd(int32_t a1) {
    // 0x1500
    int32_t v1; // 0x1500
    puts((char *)(v1 + 0x253e));
    return puts((char *)(v1 + 0x2fff));
}

// Address range: 0x1540 - 0x15ae
int32_t ww(int32_t a1) {
    // 0x1540
    int32_t v1; // 0x1540
    puts((char *)(v1 + 0x3207));
    puts((char *)(v1 + 0x3212));
    puts((char *)(v1 + 0x3226));
    puts((char *)(v1 + 0x322d));
    return puts((char *)(v1 + 0x3238));
}

// Address range: 0x15b0 - 0x15eb
int32_t xyxxd(int32_t a1) {
    // 0x15b0
    int32_t v1; // 0x15b0
    puts((char *)(v1 + 0x31cd));
    return puts((char *)(v1 + 0x3c8f));
}

// Address range: 0x15ec - 0x1604
int32_t _fini(void) {
    // 0x15ec
    int32_t v1; // 0x15ec
    return __x86_get_pc_thunk_bx(v1);
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (11.3.0)
// Detected functions: 30

